### ISSUE TITLE
Unhighlighted button text UNDER the background image?

### ISSUE THREAD

**Issue by jsonnentag** [rrirower/DP2SceneGraphWizard#98] opened 2024-03-22 01:02 UTC
I had to just do a minimal information input to see what it is supposed to look like when you are on a screen to play and episode.  Apparently now when viewing an episode's info the Play/Continue Playing button is highlighted and you can see an icon and text, but the button next to it has text only and no button icon.  The text goes from unhighlighted being white to black when the button is highlighted.

So I can now see why I never say the text in the button when it was highlighted, because I set all fonts to white, BUT I also see no text for the unactive button (which ought to be white and visible, since I have a dark background).  But there is just empty space.

So is is all unactive/not highlighted button text being written before (or under) the background image?

I can see it when there is no background image specified.  (???)

These are the 3 views when the 3 different buttons are highlighted and I have my dark background image that the white text of inactive buttons ought to be visible on.

Also, is one of the Font entries specifically for these buttons and nothing else?

![dev](https://github.com/rrirower/DP2SceneGraphWizard/assets/36777806/67431e45-ba0a-4115-8843-2b762134c19a)

![dev-1](https://github.com/rrirower/DP2SceneGraphWizard/assets/36777806/345c5658-cada-4924-82a9-4e77fa579113)

![dev](https://github.com/rrirower/DP2SceneGraphWizard/assets/36777806/1ef31f66-cb9e-46d8-a5cd-c286aca64927)

**Comment by jsonnentag** [comment] 2024-03-22 01:15
I guess I should also note that I changed all of the fonts to system fonts, except for the only 12K "genericons.regular.otf" and I think is just used for the round dot between video info/characteristics on that line under the title.

So if there is something in those buttons that won't work with system fonts that would be good to know.

**Comment by jsonnentag** [comment] 2024-03-22 01:31
Just testing again with the original ZIP from the wizard it has to be the font and something not liking to use the System Fonts rather than what it was from the wizard.  Because I can see the white text when not highlighted and black text in the the highlighted button with my selected background image.

Which of the fonts in the list is for those buttons and it is ONLY for those buttons?  (???)

I don't know about for anybody else, but for me it would be extremely helpful to have a comment associated with each font setting that says what labeling/text that font name is used for in the channel.

**Comment by jsonnentag** [comment] 2024-03-22 16:25
I just remembered something else that came to mind when first viewing the latest arrangement of things. . . .

Is there a reason why the icon for the Play or Play all or anything else isn't visible along with the text description even when the button isn't highlighted?  It seems clearer to me to have everything applicable (not Continue if nothing has been played yet, for example) visible initially and then just put a box around the active/selected button.  The way it is now the text appears but the icon for the button is only visible when it is highlighted.  (???)

I also liked the top to bottom (vertical)  listing/display of buttons better than the current horizontal version.

**Comment by rrirower** [comment] 2024-03-22 18:00
This issue is caused by the changes you've made.  The button font is set in the `DetailsScreen.brs` file in the function `SetButtonFont`.  The code uses a Roku ButtonGroup object.  As such,  the rendering of the buttons is handled by that object.

_I also liked the top to bottom (vertical) listing/display of buttons better than the current horizontal version._

Keep in mind, I cannot design the code for a specific user's specifications.  I'm trying to keep the code as generic as possible so that each user can make any changes that meet their own needs.

**Comment by jsonnentag** [comment] 2024-03-22 21:12
> Keep in mind, I cannot design the code for a specific user's specifications. I'm trying to keep the code as generic as possible so that each user can make any changes that meet their own needs.

Obviously, at some point somebody decided to change the "generic" - because the current (active on Roku) channel (based on "beta2" has things in vertical arrangement and not the current horizontal one.  :))

**Comment by jsonnentag** [comment] 2024-03-22 21:51
> This issue is caused by the changes you've made. The button font is set in the `DetailsScreen.brs` file in the function `SetButtonFont`. The code uses a Roku ButtonGroup object. As such, the rendering of the buttons is handled by that object.

OK, I found the location that lists the font it wants to use for the button.  I'm guessing it has to be a font that allows size adjustment and that is why the simple system font doesn't work right.

It appears (based on a search for "pkg:/fonts/" and going through all the files) that those 2 font settings are the only ones that are somewhere OTHER THAN in the "fontsupport.brs" file.

![image](https://github.com/rrirower/DP2SceneGraphWizard/assets/36777806/60b2835b-9558-4673-aea5-cba5cef6894f)

I'm fine with the White and Black font colors, but where are those set, since I don't see the colors specified in there.

Oh, you can see I set the font to 24 (after I pasted the "Gotham-Medium.otf" back in the fonts subdirectory) and it is much nicer.  I (and presumably everybody else) can see it now and the buttons don't look like an afterthought, kind of hidden.  :)

![dev](https://github.com/rrirower/DP2SceneGraphWizard/assets/36777806/a1931a32-8e65-4604-9a3c-81f32ce0f77d)

**Comment by jsonnentag** [comment] 2024-03-22 22:05
Oh, I was also going to say if you put the button font setting in the file with all the other ones I would suggest calling it "ButtonFont" or something so people can easily adjust just those and not have to worry about changing everything else associated with the font names already in there.

**Comment by rrirower** [comment] 2024-04-11 19:26
Font issues resolved in version 1.0.0.1.  This update should make it easier to manage screen field fonts, colors, etc.

**Closed by rrirower** 2024-04-11 19:26 UTC
Labels: wontfix
