### ISSUE TITLE
In app search function does not work with only Movies category but works fine with both Movies and series categories.

### ISSUE THREAD

**Issue by wajidbux** [rrirower/DP2SceneGraphWizard#92] opened 2024-03-04 19:36 UTC
Hi Michael I am using v1.0.0.0 beta.3 and I'm encountering a very strange problem. I have in total four channels on Roku, two have only movies and two have both movies and series, the in-app search option works perfectly with the latter but it completely freezes, the debug output is attached below

![search screen](https://github.com/rrirower/DP2SceneGraphWizard/assets/54876296/8211ec4c-7621-493d-89ef-4b21850b5323)

![search-screen](https://github.com/rrirower/DP2SceneGraphWizard/assets/54876296/9d800159-efeb-4288-96aa-d862ccaf62ff)

![BrightScript Crash Logs with Stacktraces (1)](https://github.com/rrirower/DP2SceneGraphWizard/assets/54876296/535fa8da-0ace-4b81-b741-a33f96f508fe)

the other issue is that after a particular movie or episode has finished being watched it does not automatically get removed from the continue watching row list.

**Comment by rrirower** [comment] 2024-03-04 19:50
Can you give me the feed url and the steps to reproduce the problem?

**Comment by wajidbux** [comment] 2024-03-04 19:54
feed url for movies and series
https://mangatv.dreamhosters.com/roku.json

feed url for only movies
https://movielandroku.dreamhosters.com/roku.json

after sideloading the channel the search option does not work the entire screen freezes.

**Comment by rrirower** [comment] 2024-03-04 19:56
Can you give me an example of a Search string that produces the error?

**Comment by wajidbux** [comment] 2024-03-04 19:58
you can use any movie name that shows up on the grid screen, once u click on search and type any alphabet there is a black screen of death.

**Comment by rrirower** [comment] 2024-03-04 20:08
I just ran a quick test.  It's not hanging.  It appears to be timing out processing the search because you have a large number of content items to process.  For example, your first row contains 1,580 items!

I'll have to take a closer look to see what, if anything, can be done.

**Comment by wajidbux** [comment] 2024-03-04 20:16
I agree there is a lot of content but there was no problem while the channel was in direct publisher. kindly take a look at the third screenshot as well I've been getting this error in the player task on line 103 for a long time now. this error message shows under analytics in the dashboard under channel health in the roku dashboard.
Thanks alot

**Comment by rrirower** [comment] 2024-03-06 17:14
I will have a fix for the Search issue soon.  As for the player task, do you have the Roku Ad Framework enabled?

**Comment by wajidbux** [comment] 2024-03-06 17:20
yes the RAF is enabled. Thank you for looking into the issue.

**Comment by rrirower** [comment] 2024-03-06 17:25
This seems to work with Roku's sample ad URL.  Can you provide the ad server url you are using?  And, are you specifying ad breaks?

**Comment by wajidbux** [comment] 2024-03-06 17:27
I'm using VAST3 tags.
 
https://tag.targeting.unrulymedia.com/rmp/215213/0/vast3?devId=ROKU_ADS_TRACKING_ID&w=ROKU_ADS_DISPLAY_WIDTH&h=ROKU_ADS_DISPLAY_HEIGHT&appbundle=ROKU_ADS_APP_ID&appname=Movieland&appstoreurl=https://channelstore.roku.com/details/2baedbba13b6d7a51e607e66298bd8a8/movieland&cntlen=ROKU_ADS_CONTENT_LENGTH&dnt=ROKU_ADS_LIMIT_TRACKING

**Comment by rrirower** [comment] 2024-03-06 17:41
Does the display of the player task message prevent you from submitting your channel?  It may be a false positive.

**Comment by wajidbux** [comment] 2024-03-06 17:44
No, it does not. I have already published 3 versions but that error does not seem to go away. Nothing shows up on the brightscript debugger, just the dashboard under channel analytics.

Yahoo Mail: Search, organise, conquer 
 
  On Wed, 6 Mar 2024 at 23:11, ***@***.***> wrote:   


Does the display of the player task message prevent you from submitting your channel? It may be a false positive.

**Comment by rrirower** [comment] 2024-03-06 19:04
I ran a test with your ad server URL.  I stepped through the code and everything looked OK.  I would assume what you're seeing is a false positive from Roku.  I've seen some recent posts on the forum that mention this type of thing happening elsewhere in their framework.

If you haven't already, please consider adding your experiences using this project to discussion #55

**Comment by rrirower** [comment] 2024-03-06 19:54
I may have stumbled on the player task issue.   I got the error in debug while testing some code.  It would only happen if I started a video and immediately returned to the Details screen.  An internal Roku array was not initialized for some reason.  My code relies on that array.  I should have a fix for this also.

**Comment by wajidbux** [comment] 2024-03-07 05:51
Ok. Thanks in advance and I will share my experience.

**Comment by rrirower** [comment] 2024-03-17 15:57
Resolved in beta.5 release.

**Closed by rrirower** 2024-03-17 15:57 UTC
Labels: bug
