### ISSUE TITLE
DP2SceneGraphWizard v1.0.0.0-alpha-4

### ISSUE THREAD

**Issue by fronderblash** [rrirower/DP2SceneGraphWizard#14] opened 2023-08-18 22:03 UTC
hello 
please help me on this 

After generate packages  from DP2SceneGraphWizard and i try to upload on my device and i saw this 

please what is the solution please is it my feed have error or package files 
![nnjbhgh](https://github.com/rrirower/DP2SceneGraphWizard/assets/141512200/cac85a8c-8ebc-4a8f-9015-309a3dcc02f2)

**Comment by rrirower** [comment] 2023-08-18 22:19
I'll have to take a closer look. I'll get back to you tomorrow.  It might be the way the zip was built.

**Comment by fronderblash** [comment] 2023-08-18 22:24
[HpD.zip](https://github.com/rrirower/DP2SceneGraphWizard/files/12384269/HpD.zip)

**Comment by fronderblash** [comment] 2023-08-18 22:24
that is the file

**Comment by rrirower** [comment] 2023-08-18 22:52
Btw ... Have you made any changes to the code in the original zip file?

**Comment by fronderblash** [comment] 2023-08-18 22:54
No

**Comment by ferdiworks** [comment] 2023-08-19 02:43
I to have tested this and keep getting this error V4

Application Received: 297546 bytes stored.
Install Failure: Compilation Failed.PlayerTask

**Comment by ferdiworks** [comment] 2023-08-19 02:53
Snack TV works in V3

**Comment by fronderblash** [comment] 2023-08-19 03:16
[ferdiworks](https://github.com/ferdiworks)
i don't understand
This channel is my sister channel 
please what is the solution to this

**Comment by ferdiworks** [comment] 2023-08-19 03:24
Issue solved = **Add this line to manifesrt** file **under feed link** to fix issue!

**bs_libs_required=roku_ads_lib**

**Comment by fronderblash** [comment] 2023-08-19 03:32
Thanks for this but i have Zero coding
how can i get to manifest file please can you help me Ad it

**Comment by fronderblash** [comment] 2023-08-19 03:36
or can i rebuild the package to v4

**Comment by fronderblash** [comment] 2023-08-19 03:42
![buiiu](https://github.com/rrirower/DP2SceneGraphWizard/assets/141512200/6b6114c1-212c-4385-8d98-2d949a4197f9)


if yes which can i increase to V4 i it build version, minor version  or major version please which one

**Comment by ferdiworks** [comment] 2023-08-19 03:49
The software is now V4

The output package has manifest file inside

Issue solved in V4 = Add this line to manifest file under feed link to fix issue!

bs_libs_required=roku_ads_lib

**Comment by fronderblash** [comment] 2023-08-19 04:04
i Add this line to manifest file under feed link and i click save but the package didn't save it save in another page as document

**Comment by rrirower** [comment] 2023-08-19 10:46
I'm not sure including that library is the correct fix to this issue. It's only required if the code is using the Roku advertising framework.  This version has no code for advertising as yet.  Adding this library seems like it would be appropriate if you've changed the code to work with RAF.

All this is assuming that the Roku docs are accurate.

**Comment by ferdiworks** [comment] 2023-08-19 11:10
@rrirower Got you! I understand reverting to using V3

**Comment by fronderblash** [comment] 2023-08-19 12:46
hello
please what is the solution to this
![nnjbhgh](https://github.com/rrirower/DP2SceneGraphWizard/assets/141512200/2356c918-5ff0-4997-846a-b74a3053bc5a)

**Comment by rrirower** [comment] 2023-08-19 12:50
The solution is to be patient while the problem is being investigated.

**Comment by fronderblash** [comment] 2023-08-19 12:51
okay Thanks

**Comment by fronderblash** [comment] 2023-08-19 23:29
???

**Comment by rrirower** [comment] 2023-08-20 18:14
Fixed with alpha-4

**Closed by rrirower** 2023-08-20 18:14 UTC
